src/Entity/Tontine.php
<?php

namespace App\Entity;

use App\Repository\TontineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=TontineRepository::class)
 * @ORM\Table (
 *     name="tontine",
 *      uniqueConstraints={@ORM\UniqueConstraint(columns={"numcomp", "ranglivret"})}
 * )
 * @ORM\HasLifecycleCallbacks()
 */
class Tontine
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $meconomie;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $numordre;

    /**
     * @ORM\Column(type="date" , nullable=true)
     */
    private $dateinscr;

    /**
     * @ORM\Column(type="integer")
     */
    private $ranglivret;

    /**
     * @ORM\Column(type="string")
     */
    private $reflivret;

    /**
     * @ORM\Column(type="smallint", nullable=true))
     */
    private $nbmois;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mcredit;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mdebit;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $avance;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbfeuillet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $finfeuillet;


    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbmaxappoint;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateraappoint;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"reflivret","ranglivret","nbfeuillet","nbmaxappoint"})
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tontines")
     * @ORM\JoinColumn(nullable=false)
     */
    private $createdBy;

    /**
     * @ORM\Column(type="date")
     */
    private $createdOn;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tontines")
     */
    private $editedBy;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $editedOn;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="tontines")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Agence::class, inversedBy="tontines")
     * @ORM\JoinColumn(nullable=false)
     */
    private $agence;

    /**
     * @ORM\ManyToOne(targetEntity=Compte::class, inversedBy="tontines")
     * @ORM\JoinColumn(nullable=false)
     */
    private $compte;

    /**
     * @ORM\OneToMany(targetEntity=Operation::class, mappedBy="tontine")
     */
    private $operations;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Note;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $bloqueravance;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $feuillet;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $numcomp;

    /**
     * @ORM\OneToMany(targetEntity=Detailtontine::class, mappedBy="tontine")
     */
    private $detailtontines;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $appointrest;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $solde;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $niveau;

    /**
     * @ORM\OneToMany(targetEntity=Avancement::class, mappedBy="tontine")
     */
    private $avancements;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $mtcollecte;

    public function __construct()
    {
        $this->setDateinscr(new \DateTime('now'));
        $this->actif=true;
        $this->feuillet=1;
        $this->numordre=0;
        $this->meconomie=0;
        $this->nbfeuillet=0;
        $this->mtcollecte=0; // Sinon la rêquête de solde va envoyer 0
        $this->avance=0; // Sinon la rêquête de solde va envoyer 0
        $this->detailtontines = new ArrayCollection();
        $this->operations = new ArrayCollection();
        $this->avancements = new ArrayCollection();
    }


    /**
     * @ORM\PrePersist()
     */
    public function datecreated()
    {
        $this->setCreatedOn(new \DateTime('now'));
    }

    /**
     * @ORM\PreUpdate()
     */
    public function dateupdated()
    {
        $this->setEditedOn(new \DateTime('now'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMeconomie(): ?int
    {
        return $this->meconomie;
    }

    public function setMeconomie(int $meconomie): self
    {
        $this->meconomie = $meconomie;

        return $this;
    }

    public function getNumordre(): ?int
    {
        return $this->numordre;
    }

    public function setNumordre(int $numordre): self
    {
        $this->numordre = $numordre;

        return $this;
    }

    public function getDateinscr(): ?\DateTimeInterface
    {
        return $this->dateinscr;
    }

    public function setDateinscr( $dateinscr): self
    {
        $this->dateinscr = $dateinscr;

        return $this;
    }



    public function getNbmois(): ?int
    {
        return $this->nbmois;
    }

    public function setNbmois(int $nbmois): self
    {
        $this->nbmois = $nbmois;

        return $this;
    }

    public function getMcredit(): ?int
    {
        return $this->mcredit;
    }

    public function setMcredit(?int $mcredit): self
    {
        $this->mcredit = $mcredit;

        return $this;
    }


    public function getAvance(): ?int
    {
        return $this->avance;
    }

    public function setAvance(?int $avance): self
    {
        $this->avance = $avance;

        return $this;
    }


    public function getFinfeuillet(): ?string
    {
        return $this->finfeuillet;
    }

    public function setFinfeuillet(?string $finfeuillet): self
    {
        $this->finfeuillet = $finfeuillet;

        return $this;
    }


    public function getNbmaxappoint(): ?int
    {
        return $this->nbmaxappoint;
    }

    public function setNbmaxappoint(?int $nbmaxappoint): self
    {
        $this->nbmaxappoint = $nbmaxappoint;

        return $this;
    }

    public function getDateraappoint(): ?\DateTimeInterface
    {
        return $this->dateraappoint;
    }

    public function setDateraappoint(?\DateTimeInterface $dateraappoint): self
    {
        $this->dateraappoint = $dateraappoint;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->createdOn;
    }

    public function setCreatedOn(?\DateTimeInterface $createdOn): self
    {
        $this->createdOn = $createdOn;

        return $this;
    }

    public function getEditedBy(): ?User
    {
        return $this->editedBy;
    }

    public function setEditedBy(?User $editedBy): self
    {
        $this->editedBy = $editedBy;

        return $this;
    }

    public function getEditedOn(): ?\DateTimeInterface
    {
        return $this->editedOn;
    }

    public function setEditedOn(?\DateTimeInterface $editedOn): self
    {
        $this->editedOn = $editedOn;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getAgence(): ?Agence
    {
        return $this->agence;
    }

    public function setAgence(?Agence $agence): self
    {
        $this->agence = $agence;

        return $this;
    }

    public function getCompte(): ?Compte
    {
        return $this->compte;
    }

    public function setCompte(?Compte $compte): self
    {
        $this->compte = $compte;

        return $this;
    }
    public function __toString(){
        return $this ->reflivret;
    }

//    /**
//     * @return Collection|Operation[]
//     */
//    public function getOperations(): Collection
//    {
//        return $this->operations;
//    }
//
//    public function addOperation(Operation $operation): self
//    {
//        if (!$this->operations->contains($operation)) {
//            $this->operations[] = $operation;
//            $operation->setTontine($this);
//        }
//
//        return $this;
//    }
//
//    public function removeOperation(Operation $operation): self
//    {
//        if ($this->operations->removeElement($operation)) {
//            // set the owning side to null (unless already changed)
//            if ($operation->getTontine() === $this) {
//                $operation->setTontine(null);
//            }
//        }
//
//        return $this;
//    }

    public function getReflivret(): ?string
    {
        return $this->reflivret;
    }

    public function setReflivret(string $reflivret): self
    {
        $this->reflivret = $reflivret;

        return $this;
    }

    public function getMdebit(): ?int
    {
        return $this->mdebit;
    }

    public function setMdebit(?int $mdebit): self
    {
        $this->mdebit = $mdebit;

        return $this;
    }


    public function getNote(): ?string
    {
        return $this->Note;
    }

    public function setNote(?string $Note): self
    {
        $this->Note = $Note;

templates/collecte/_delete_form.html.twig
<form method="post" action="{{ path('collecte_delete', {'id': collecte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ collecte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/collecte/_form.html.twig
<div class="row" style="margin-left: auto">

   <div class="row col-md-12" >
      <div class="col-md-5 ">
         {{ form_label(form_detail.tontine) }}
         {{ form_widget(form_detail.tontine) }}
         {{ form_errors(form_detail.tontine) }}

      </div>
      <div class="col-md-5 offset-2">
         {{ form_label(form_operation.nomcomplet) }}
         {{ form_widget(form_operation.nomcomplet) }}
         {{ form_errors(form_operation.nomcomplet) }}

      </div>
   </div>

   <div class="row col-md-12" >
      <div class="col-md-5 ">
         {{ form_label(form_tontine.meconomie) }}
         {{ form_widget(form_tontine.meconomie) }}
         {{ form_errors(form_tontine.meconomie) }}
      </div>
      <div class="col-md-5 offset-2">
         {{ form_label(form_tontine.ranglivret) }}
         {{ form_widget(form_tontine.ranglivret) }}
         {{ form_errors(form_tontine.ranglivret) }}

      </div>
   </div>
   <div class="row col-md-12" >
      <div class="col-md-5 ">
         {{ form_label(form_tontine.numordre) }}
         {{ form_widget(form_tontine.numordre) }}
         {{ form_errors(form_tontine.numordre) }}
      </div>
      <div class="col-md-5 offset-2">
         {{ form_label(form_tontine.feuillet) }}
         {{ form_widget(form_tontine.feuillet) }}
         {{ form_errors(form_tontine.feuillet) }}
      </div>
   </div>

   <div class="row col-md-12" >
      <div class="col-md-5 offset-1">
         {{ form_label(form_operation.montantop) }}
         {{ form_widget(form_operation.montantop) }}
         {{ form_errors(form_operation.montantop) }}

      </div>
      <div class="col-md-6 offset-1">
         {{ form_label(form_operation.dateop) }}
         {{ form_widget(form_operation.dateop) }}
         {{ form_errors(form_operation.dateop) }}

      </div>
   </div>

   <div class="row col-md-12" >
      <div class="col-md-5 offset-2">
         {{ form_label(form_operation.operant) }}
         {{ form_widget(form_operation.operant) }}
         {{ form_errors(form_operation.operant) }}

      </div>
      <div class="col-md-5" id="cachet">
         {{ form_label(form_tontine.appointrest) }}
         {{ form_widget(form_tontine.appointrest) }}
         {{ form_errors(form_tontine.appointrest) }}

      </div>
      <div class="col-md-5 offset-2">
         {{ form_label(form_operation.note) }}
         {{ form_widget(form_operation.note) }}
         {{ form_errors(form_operation.note) }}

      </div>
   </div>



</div>

templates/collecte/annuler.html.twig
<a href="#" data-toggle="modal" data-target="#{{ collecte.slug }}">
        {#<i class="fa fa-eraser"></i>#}{{ collecte.libelleop }}</a>


<div class="modal fade" id="{{ collecte.slug }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">
                    Etes-vous sûrs de bien vouloir <b><em style="color: #c61b3d">annuler</em></b> l'opération (contre-écriture) ?
                </h4>
            </div>
            <div class="modal-footer">
                <a href="{{ path('collecte_annuler',{'slug' : collecte.slug}) }}" class="btn btn-primary">Oui</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Non</button>
            </div>
        </div>
    </div>
</div>

templates/collecte/collecte.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Admin{% endblock %}

{% block nav %}
    {#{% if actif is same as('accueil') %} class="active" {% endif %}#}
    {% set actif='operations' %}
    {{ parent() }}
    {#{% set actif='parametre' %}
    {% include 'nav_parm.html.twig' %}#}
{% endblock %} {#End nav#}

 {% block path %}
     <li><a href="{{path('Accueil')}}">Opérations</a></li>
    {# <li><a href="#">Branches</a></li>#}
     <li class="active">Collectes</li>
     {#<li><a href="sign-in.html">Sign In Form</a></li>#}
 {% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.getElementById('cachet').style.display="";
        function valide(ferme){

            // Contrôle des champs
            if(document.getElementById('collecte_tontine').value.length < 1){
                surligneAvecMessage(document.getElementById('collecte_tontine'),
                    true,'Veuillez renseigner un numéro correct de livret');
                return false;
            }else {
                if(document.getElementById('operation_tontine_montantop').value.length < 1){
                    surligneAvecMessage(document.getElementById('operation_tontine_montantop'),
                        true,'Veuillez renseigner un montant pour l\'operation');
                    return false;
                }else {
                    montantOp=document.getElementById('operation_tontine_montantop').value
                    miseJournaliere=document.getElementById('form_tontine_meconomie').value

                    if((montantOp % miseJournaliere) !==0){ // On calcule le modulo du montantop sur la mise
                        surligneAvecMessage(document.getElementById('operation_tontine_montantop'),
                            true,'Le montant de l\'opéraration doit être un multiple de la mise');
                        return false;
                    }else {
                        if(document.getElementById('operation_tontine_dateop_date_day').value.length < 1 ||
                            document.getElementById('operation_tontine_dateop_date_month').value.length < 1 ||
                            document.getElementById('operation_tontine_dateop_date_year').value.length < 4
                        ){
                            surligneAvecMessage(document.getElementById('operation_tontine_dateop_date_day'),
                                true,'Veuillez renseigner une date valide');
                            return false;
                        }else {

                            restAppoint=document.getElementById('form_tontine_appointrest').value;
                            if((montantOp/miseJournaliere)>restAppoint){
                                surligneAvecMessage(document.getElementById('operation_tontine_montantop'),
                                    true,'Le montant dépasse le nombre d\'appointements restants : '+restAppoint);
                                return false;

                            }else{
                                // Requete AJAX pour envoyer les données aux serveur après confirmation
                                $("body").overhang({
                                    type: "confirm",
                                    message: "Voulez-vous vraiment valider l'opération?",
                                    callback: function (value) {
                                        var response = value ? "Oui" : "No";
                                        if(response === 'Oui'){
                                            $.ajax({
                                                url: "/operation/collecte/nouvel",
                                                method: "POST",
                                                data: $('#form_collecte').serialize(),
                                                success: function (data) {
                                                   /* if(typeof data.erreur !== 'undefined'){*/
                                                        if (ferme === true){
                                                            $('#form_collecte')[0].reset();
                                                            $('.close').click();
                                                            if($('#collecte_table').html(data)){
                                                                $("body").overhang({
                                                                    type: "success",
                                                                    message: "Enregistremnt bien fait!!"
                                                                });
                                                                //window.location.reload();
                                                            }
                                                        }else { // D'autres enregistrement
                                                            $("body").overhang({
                                                                type: "success",
                                                                message: "Enregistremnt bien fait!!"
                                                            });
                                                        }
                                                    /*}else {
                                                        $("body").overhang({
                                                            type: "error",
                                                            message: data.message,
                                                            closeConfirm: true
                                                        });
                                                    }*/

                                                },
                                                error: function (data) {
                                                    $("body").overhang({
                                                        type: "error",
                                                        message: "Whoops! Quelque chose ne va pas!",
                                                        closeConfirm: true
                                                    });
                                                }

                                            })/*.then(res => window.location.reload());*/
                                        }
                                    }
                                });
                            }
                        }
                    }
                }
            }

        }


        // Remplissage  des champs
        function remplirChamps() {
            if( document.getElementById('collecte_tontine').value !== ''
            ){

                $.ajax({
                    url: "{{ path('collecte_remplirchamp') }}",
                    method: "POST",
                    data: $('#form_collecte').serialize(),
                    success: function (data) {
                        //console.log(data);
                        // Remplir les champ après avoir recuperer la reference
                        document.getElementById('operation_tontine_nomcomplet').value=data.nomcomplet;
                        document.getElementById('form_tontine_meconomie').value=data.meconomie;
                        document.getElementById('form_tontine_ranglivret').value=data.ranglivret;
                        document.getElementById('form_tontine_numordre').value=data.numordre;
                        document.getElementById('form_tontine_feuillet').value=data.feuillet;
                        document.getElementById('form_tontine_appointrest').value=data.appRestant;

                        // Focus dans le champ Montant
                        document.getElementById('operation_tontine_montantop').focus();

                    },

                })
                /* });*/
            }

        }


    </script>

    <script>
        $('select[data-select="true"]').select2(
            {
                dropdownParent: $("#myModal"),
                width: '100%',
            }
        );
    </script>

{% endblock %}

templates/collecte/collecte_table.html.twig
{% for collecte in collectes %}
    <tr>
        <td>{{ collecte.numcomp }}</td>
        <td>
           {# L'annuation serait possible lorsqu'elle intervient le même jour que l'operation#}
            {% if collecte.cancel is same as true %}
                {{ collecte.libelleop }}
            {% elseif
                "now" | date('Y-m-d') is same as(collecte.datecomptabilisation|date('Y-m-d'))
                and collecte.sens is same as ('C')
            %}
                {% include('collecte/annuler.html.twig') %}
            {% else %}
            {{ collecte.libelleop }}
            {% endif %}
        </td>
        <td>{{ collecte.dateop | date('d/m/Y H:m') }}</td>
        <td>{{ collecte.montantop | number_format(0,0,' ') }}</td>
        <td>{{ collecte.sens  }}</td>
        <td>{{ collecte.client }}</td>
        <td>
            {#{% include('collecte/viewmodal.html.twig') %}#}
        </td>
    </tr>
{% endfor %}

templates/collecte/deletemodal.html.twig
<a type="button" class="btn  btn-danger" data-toggle="modal" data-target="#{{ collecte.id }}">
    <i class="fa fa-trash-o"></i>
    Supprimer
</a>

<!-- Modal -->
<div class="modal fade " id="{{ collecte.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="color: #000000">
    <div class="modal-dialog modal-lg" role="document"  >
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Suppression collecte</h4>
            </div>
            <div class="modal-body">
                <h2>Supprimer la collecte </h2>

                    <h5> Etes-vous certain de vouloir supprimer cette collecte " <em style="color: red">{{ collecte.libelle }}</em>" ? </h5>

                <form method="post" action="{{ path('collecte_delete', {'id': collecte.id}) }}" {#onsubmit="return confirm('Are you sure you want to delete this item?');"#}>
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ collecte.id) }}">
                    <button class="btn btn-danger">
                        <i class="fa fa-trash-o"></i>
                        Supprimer
                    </button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

templates/collecte/edit.html.twig
{% extends 'collecte/collecte.html.twig' %}



{% block content %}

    <h1>Modification de la operation_tontine</h1>
    <div class="col-md-8">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-default" href="{{ path('collecte_index') }}">
                    <i class="fa fa-chevron-left"></i>
                    Retour
                </a>
            </div>
            <div class="col-md-1 col-md-offset-3">
                <input class="btn btn-primary" type="submit" value="Modifier" />
                {{ form_end(form) }}
            </div>
            <div class="col-md-4"></div>
            {% if is_granted('ROLE_ADMIN') and is_granted('ROLE_SUP') %}
            <div class="col-md-1 col-md-offset-5">
                {% include('collecte/deletemodal.html.twig') %}
            </div>
             {% endif %}
        </div>
    </div>

{% endblock %}

templates/collecte/index.html.twig
{% extends 'collecte/collecte.html.twig' %}


{% block content %}
    <div class="card mb-3" >
        <div class="card-header">
            <h2>
                <i class="fa fa-table" ></i>
                Liste des collectes</h2></div>
        <div class="card-body" >
            <div class="row">
                <div class="col-md-2" id="add-modal">
                    {% include('collecte/new.html.twig') %}
                </div>

                {#<div class="offset-8 col-md-2 ">
                    <a href="#" class="btn btn-success ">
                        <i class="fa fa-print"></i>
                        Imprimer
                    </a>
                </div>#}
            </div>
            <hr>
            <table class="table table-bordered " id="datatable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>N° Compte</th>
                    <th>Libellé</th>
                    <th>Date/heure</th>
                    <th>Montant</th>
                    <th>Sens</th>
                    <th>Client</th>
                    <th>Vue</th>
                </tr>
                </thead>
                <tbody id="collecte_table">
                {{ include('collecte/collecte_table.html.twig') }}
                </tbody>
            </table>
        </div>
    </div>

    <div class="card-footer small text-muted">Hier à 11:59 </div>

{% endblock %}

templates/collecte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Collecte{% endblock %}

{% block body %}
    <h1>Collecte</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ collecte.id }}</td>
            </tr>
            <tr>
                <th>Libelleclt</th>
                <td>{{ collecte.libelleclt }}</td>
            </tr>
            <tr>
                <th>Montantclt</th>
                <td>{{ collecte.montantclt }}</td>
            </tr>
            <tr>
                <th>Dateclt</th>
                <td>{{ collecte.dateclt ? collecte.dateclt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>CreatedOn</th>
                <td>{{ collecte.createdOn ? collecte.createdOn|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>EditedOn</th>
                <td>{{ collecte.editedOn ? collecte.editedOn|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ collecte.slug }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('collecte_index') }}">back to list</a>

    <a href="{{ path('collecte_edit', {'id': collecte.id}) }}">edit</a>

    {{ include('collecte/_delete_form.html.twig') }}
{% endblock %}

templates/collecte/viewmodal.html.twig
<a style="cursor: pointer"  data-toggle="modal" data-target="#{{ collecte.id }}">
    <i style="font-size: 20px" class="fa fa-eye "></i>
</a>

<!-- Modal -->
<div class="modal fade " id="{{ collecte.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="color: #000000">
    <div class="modal-dialog modal-lg" role="document"  >
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Détails collecte</h4>
            </div>
            <div class="modal-body">
                <table class="table-bordered table" style="background-color: #868e96">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ collecte.id }}</td>
                    </tr>
                    <tr>
                        <th>Référence</th>
                        <td>{{ collecte.reflivret }}</td>
                    </tr>
                    <tr>
                        <th>Montant Economie</th>
                        <td>{{ collecte.meconomie }}</td>
                    </tr>
                    <tr>
                        <th>Nombre feuillets</th>
                        <td>{{ collecte.nbfeuillet }}</td>
                    </tr>
                    <tr>
                        <th>Note</th>
                        <td>{{ collecte.note }}</td>
                    </tr>
                    <tr>
                        <th>Etat</th>
                        <td>{{ collecte.actif ? 'Actif' : 'Non actif' }}</td>
                    </tr>

                    <tr>
                        <th>Enregistré le</th>
                        <td>
                            {{ collecte.createdOn ? collecte.createdOn |date('d/m/Y H:i:s') : ''  }} <br>
                            Par {{ collecte.createdBy }}
                        </td>
                    </tr>

                    <tr>
                        <th>Modifié le</th>
                        <td>
                            {{ collecte.editedOn ? collecte.editedOn |date('d/m/Y H:i:s') : ''  }} <br>
                            Par {{ collecte.editedBy }}
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="row" >
                    <button type="button" class="btn btn-info" data-dismiss="modal">
                        <i class="fa fa-chevron-left"></i>
                        Retour à la liste
                    </button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                {#<button type="button" class="btn btn-primary">Imprimer</button>#}
            </div>
        </div>
    </div>
</div>